name: Build All
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
      label:
        type: string
        required: false
        default: 'VS Code Extensions'
  workflow_dispatch: 
    inputs:
      branch:
        type: string
        required: false
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Configure Git for private repo access
        run: git config --global --add url."https://${{ secrets.IDEE_GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: npm install
      - run: npm --version
      - run: node --version
