name: Integration Tests Windows
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false
  workflow_dispatch: 

jobs:
  windows-integration-tests:
    runs-on: windows-latest
    timeout-minutes: 60
    env: 
      CODE_LOGS: ${{ github.workspace }}/crash-logs
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm config set scripts-prepend-node-path true
      - run: npm install -g sfdx-cli
      - run: npm install -g junit-merge
      - run: npm ci
      - run: npm run compile
      - run: npm run test:integration-tests-without-system-tests
      - name: 'upload crash logs'
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: crash-logs-${{ github.run_id }}-${{ github.run_number }}-${{ github.event.repository.updated_at }}
          path: ${{ env.CODE_LOGS }}
          retention-days: 3
        
