name: VSCode Publish

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    outputs:
      result:
        description: Set to published if the push to the VSCode marketplace was successful
        value: ${{ jobs.publish.outputs.result }}
      status: 
        description: Set to complete if all tasks associated with the workflow were successful.
        value: ${{ jobs.mergeDevelop.outputs.status }}
  workflow_dispatch:  
    inputs:
      version:
        type: string
        required: true

# There are two outputs that are a result of running this workflow
# The steps.publsh.outputs.result is an indicator that the pulish to the vscode marketplace succeeded.
# The steps.mergeDevelop.outputs.status is an indicator that all the publish steps completed.
jobs: 
  build-all:
    uses: ./.github/workflows/buildAll.yml
    with:
      branch: 'main'
      label: ${{ inputs.version }}
  gitTag: 
    runs-on: ubuntu-latest
    needs: ['build-all']
    env: 
      RELEASE_VERSION: ${{ inputs.version }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: ./.github/actions/gitConfig
        with:
          email: ${{ secrets.IDEE_GH_EMAIL }}
      - run: |
            git tag v${{ env.RELEASE_VERSION }}
            git push origin v${{ env.RELEASE_VERSION }}
  githubRelease:
    runs-on: ubuntu-latest
    needs: ['build-all']
    env: 
      RELEASE_VERSION: ${{ inputs.version }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: ./.github/actions/gitConfig
        with:
          email: ${{ secrets.IDEE_GH_EMAIL }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.version }}
          path: ./extensions
      - name: Display downloaded vsix files
        run: ls -R ./extensions
      - run: gh release create v${{ env.RELEASE_VERSION }} ./extensions/**/*.vsix --title "Release v${{ env.RELEASE_VERSION }}" --notes-file ./packages/salesforcedx-vscode/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}

  mergeDevelop:
    needs: [githubRelease]
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.complete.outputs.status }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - uses: ./.github/actions/gitConfig
        with:
          email: ${{ secrets.IDEE_GH_EMAIL }}
      - run: |
          git checkout develop
          git pull
          git merge main --commit --no-edit
          git push origin develop
      - id: complete
        run: |
         echo "status=complete" >> $GITHUB_OUTPUT
      - id: finish
        run: |
         echo "VSCode Publish Success"
         
