name: Publish in Open VSX Registry
on:
  release:
    # This limits the workflow to releases that are not pre-releases 
    # From the docs: A release was published, or a pre-release was changed to a release.
    types: [ released ]
    
jobs:
  githubRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Create remote release
        run: |
          mkdir ./releases
          gh release download -D ./releases ${{ github.event.release.tagName}} -p "*.vsix"
          ls -l ./releases
          gh release create "${{ github.event.release.name }}" ./releases/*.vsix --title "${{ github.event.release.title }}" --notes-file ./CHANGELOG.md -R forcedotcom/Einstein-GPT-for-Developers
        env:
          GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}

