name: Publish in Microsoft Marketplace
on:
  release:
    # This limits the workflow to releases that are not pre-releases 
    # From the docs: A release was published, or a pre-release was changed to a release.
    types: [ released ]
  #  Button for publishing main branch in case there is a failure on the release.
  workflow_dispatch:
    
jobs:
  
  prepare-environment-from-main:
    name: 'Get Release Version'
    runs-on: ubuntu-latest
    environment: publish
    outputs:
      RELEASE_VERSION: ${{ steps.getMainVersion.outputs.version }}
      GUS_BUILD: ${{ steps.getGusBuild.outputs.gusBuild}}
      SF_CHANGE_CASE_SCHEDULE_BUILD: ${{ steps.getScheduledBuild.outputs.sfChangeCaseScheduleBuild }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - id: getMainVersion
        run: |
          echo "version="$(node -pe "require('./packages/salesforcedx-vscode/package.json').version")"" >> $GITHUB_OUTPUT
      - run: echo "Main Version is ${{ steps.getMainVersion.outputs.version }}"
      - id: getGusBuild
        run: | 
          echo "gusBuild=${{ steps.getMainVersion.outputs.version }}" >> $GITHUB_OUTPUT
      - run: echo "GUS BUILD is ${{ steps.getGusBuild.outputs.gusBuild }}"
      - id: getScheduledBuild
        run: | 
          echo "sfChangeCaseScheduleBuild=offcore.tooling.${{ steps.getMainVersion.outputs.version }}" >> $GITHUB_OUTPUT
      - run: echo "SF_CHANGE_CASE_SCHEDULE_BUILD is ${{ steps.getScheduledBuild.outputs.sfChangeCaseScheduleBuild }}"\

  publish:
    needs: ['prepare-environment-from-main']
      
    runs-on: ubuntu-latest
    env: 
      VSCE_PERSONAL_ACCESS_TOKEN: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      PUBLISH_VERSION: ${{ needs.prepare-environment-from-main.outputs.RELEASE_VERSION }}
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    steps: 
      - name: downloadExtensionsFromRelease
        run: | 
          mkdir ./extensions
          echo v${{ env.PUBLISH_VERSION }} 
          gh release download v${{ env.PUBLISH_VERSION }} -D ./extensions

    
