name: Publish in Open VSX Registry
on:
  release:
    # This limits the workflow to releases that are not pre-releases 
    # From the docs: A release was published, or a pre-release was changed to a release.
    types: [ released ]
    
jobs:
  githubRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'
          token: ${{ secrets.IDEE_GH_TOKEN }}
      - name: Create remote release
        run: |
          mkdir ./releases
          echo "1"
          gh release download -D ./releases ${{ github.event.release.tagName}} -p "*.vsix"
          echo "2"
          ls -l ./releases
          echo "3"
          gh release create "${{ github.event.release.tag_name }}" ./releases/*.vsix --title "${{ github.event.release.name }}" --notes "${{ github.event.release.body }}" -R forcedotcom/Einstein-GPT-for-Developers
          echo "4"
        env:
          GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}

