name: Test Release
on:
  release:
    types: [published]
    

env:
  TAG_NAME: ${{ github.event.release.tag_name }}
jobs:

  find-release-type: 
    output:
      type: ${{step.find.output.type}}
    steps: 
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - run: echo "Tag name is ${{ env.TAG_NAME }}"
      - run: echo ${{ github.event.release }}
      
